//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace MetStation.Models
{
    
    
    public partial class Uzytkownicy
    {
        [Required(ErrorMessage = "Podaj nazwê u¿ytkownika!")]
        public string Uzytkownik { get; set; }
        [Required(ErrorMessage = "Podaj has³o u¿ytkownika!")]
        public string Haslo { get; set; }
        public string ConfirmPassword { get; set; }
        public string Email { get; set; }

    }
}
